
HELP_ARGUMENT = "--help"

MIN_DISTANCE = 0.6

GENERATED_FACE_FILENAME = "GEN FACE"

DEFAULT_ATTACK_SIZE = 1000

DEFAULT_FACE_DIR = "faces/"
DEFAULT_FACES_CSV_NAME = "features.csv"
DEFAULT_MATCHES_CSV_NAME = "matches.csv"